export const environment = {
    production: false,
    apiURL: 'http://localhost:3001/api',
    retry: 0,
    googleClientId: '',
    googleMapsApiKey: '',
    webSocketUrl: 'http://localhost:3001',
    vkAppId: '',
    host: 'http://localhost:4200',
    stripePublicKey: '',
    facebookClientId: '',
    imageKitPublicKey: '',
    imageKitUrlEndpoint: '',
    imageKitAuthenticationEndpoint: '',
    s3path: '',
};
