version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:14.14.0
        steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: yarn
            - run:
                  name: Run stage build
                  command: yarn build --configuration=staging

    deploy:
        docker:
            - image: circleci/node:14.14.0
        steps:
            - checkout

            - store_artifacts:
                  path: /dist
                  destination: smart-desk-frontend

#       - run:
#           name: Connect via SSH and run deploy script
#           command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "cd /var/www; ./deploy_backend.sh;"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
