name: Build Dev
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Build Dev

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Build Project
              run: |
                  npm install -g yarn
                  yarn
                  node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --configuration=staging

            - name: rsync deployments
              uses: burnett01/rsync-deployments@5.2
              with:
                  switches: -avzr --delete
                  path: dist
                  remote_path: /var/www/dev/smart-desk-frontend
                  remote_host: ${{ secrets.SSH_HOST }}
                  remote_user: ${{ secrets.SSH_USERNAME }}
                  remote_key: ${{ secrets.SSH_KEY }}
