name: Build Dev
on:
    push:
        branches: [master]

jobs:
    deploy:
        name: Build Dev

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Connect to Server via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd /var/www
                      ./deploy_frontend_dev.sh
