name: Build Staging
on:
    push:
        branch: [master]

jobs:
    build:
        name: Build Staging

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x

            - name: Install Yarn
              run: npm install -g yarn

            - name: Yarn install
              run: yarn

            - name: Yarn build
              run: yarn build --configuration=staging

            - uses: actions/upload-artifact@v2
              with:
                  name: smart-desk-frontend-staging
                  path: dist/
