name: Build Demo
on:
    push:
        branches: [demo]

jobs:
    deploy:
        name: Build Demo

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Build Project
              run: |
                  npm install -g yarn
                  git checkout demo
                  yarn
                  node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --configuration=production

            - name: Copy Files
              uses: burnett01/rsync-deployments@5.2
              with:
                  switches: -avzr --delete
                  path: dist
                  remote_path: /var/www/demo/smart-desk-frontend
                  remote_host: ${{ secrets.SSH_HOST }}
                  remote_user: ${{ secrets.SSH_USERNAME }}
                  remote_key: ${{ secrets.SSH_KEY }}
