# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Test

on:
    pull_request:
        type: [opened]

jobs:
    build:
        name: Test

    runs-on: ubuntu-latest

steps:
    - uses: actions / checkout@v1
    - name: Use Node.js 12.8
    uses: actions/setup-node@v1
    with:
        node-version: 12.8
    - name: Install dependencies
        run: yarn install
    - name: Build
        run: yarn run build --prod
    - name: Test
        run: yarn test
    - name: E2E
        run: yarn run e2e
